name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 2 * * *' # Runs every day at 02:00
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog post
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull in latest post
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://tim-tiefenbach.de/post/index.xml"
          max_post_count: 1
          template: "[$title]($url) "
